trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-first-project'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch \
        --account-name scazureproject \
        --account-key $(AZURE_STORAGE_KEY) \
        --destination '$web' \
        --source . \
        --overwrite